version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    container_name: blueprint-service
    ports:
      - '3202:3202'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
